"set fencs=utf-8,GB18030,ucs-bom,default,latin1
set vb t_vb=
set fileencodings=utf-8,gbk,ucs-bom,cp936,big5
"set fileencodings=utf-8,gb2312,gbk,gb18030,big5
set fenc=utf-8
set enc=utf-8
set termencoding=utf-8
set expandtab ts=4 sw=4 sts=4 tw=100
set mouse=a                 " Automatically enable mouse usage
"set mousehide               " Hide the mouse cursor while typing

set smarttab "智能制表符
set autoindent "自动缩进
set smartindent "只能缩进
set number "显示行号
set backspace=indent,eol,start "backspace键的工作方式
set ruler "设置在编辑过程中右下角显示光标的行列信息
"在状态栏显示正在输入的命令
set showcmd
"突出现实当前行列
set cursorline
"set cursorcolumn
"设置匹配模式 类似当输入一个左括号时会匹配相应的那个右括号
set showmatch
"设置搜索时忽略大小写
set ignorecase

"设置Tab宽度
set tabstop=4
"设置自动对齐空格数
set shiftwidth=4
"设置按退格键时可以一次删除4个空格
set softtabstop=4
"设置按退格键时可以一次删除4个空格
set smarttab
"将Tab键自动转换成空格 真正需要Tab键时使用[Ctrl + V + Tab]
set expandtab

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

"Launch vim and run :PluginInstall
"To install from command line: vim +PluginInstall +qall

call vundle#begin()

"使用Vundle来管理Vundle
Plugin 'gmarik/vundle'

Plugin 'scrooloose/nerdtree'    "文件浏览

Plugin 'majutsushi/tagbar'      "代码符号

"Plugin 'wesleyche/SrcExpl'      "类似sourceInsight的代码预览窗口

"PowerLine插件 状态栏增强展示
Plugin 'Lokaltog/vim-powerline'
"vim有一个状态栏 加上powline则有两个状态栏
set laststatus=2
set t_Co=256
let g:Powline_symbols='fancy'

call vundle#end()            " required

filetype plugin indent on    " required

"vundle设置完毕

syntax on

let g:tagbar_ctags_bin='/usr/local/bin/ctags'
"let g:tagbar_left = 1
let g:Tlist_Exit_OnlyWindow = 1

nnoremap ,tt :TagbarToggle<CR>

"let NERDTreeWinPos='right'

nnoremap <C-e> :NERDTreeToggle<CR>

"nmap <F4> :SrcExplToggle<CR>
"let g:Srcexpl_winHeight = 8
" // Set 100 ms for refreshing the Source Explorer 
"let g:SrcExpl_refreshTime = 100
" // Set "Enter" key to jump into the exact definition context 
"let g:SrcExpl_jumpKey = "<ENTER>"
" // Set "Space" key for back  the definition context 
"let g:SrcExpl_gobackKey = "<SPACE>"
"let g:SrcExpl_pluginList = [
"        \ "__Tag_List__",
"        \ "_NERD_tree_"
"        \]

set tags=tags;  "搜刮上一级建树的tag
set autochdir
