/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "acsuser_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




User::~User() throw() {
}


void User::__set_uid(const std::string& val) {
  this->uid = val;
}

void User::__set_uname(const std::string& val) {
  this->uname = val;
}

void User::__set_usex(const bool val) {
  this->usex = val;
}

void User::__set_uage(const int16_t val) {
  this->uage = val;
}

const char* User::ascii_fingerprint = "E48A6B2623C488281E3E50E5732AA7A0";
const uint8_t User::binary_fingerprint[16] = {0xE4,0x8A,0x6B,0x26,0x23,0xC4,0x88,0x28,0x1E,0x3E,0x50,0xE5,0x73,0x2A,0xA7,0xA0};

uint32_t User::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->uid);
          this->__isset.uid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->uname);
          this->__isset.uname = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->usex);
          this->__isset.usex = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->uage);
          this->__isset.uage = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t User::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("User");

  xfer += oprot->writeFieldBegin("uid", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->uid);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("uname", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->uname);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("usex", ::apache::thrift::protocol::T_BOOL, 3);
  xfer += oprot->writeBool(this->usex);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("uage", ::apache::thrift::protocol::T_I16, 4);
  xfer += oprot->writeI16(this->uage);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(User &a, User &b) {
  using ::std::swap;
  swap(a.uid, b.uid);
  swap(a.uname, b.uname);
  swap(a.usex, b.usex);
  swap(a.uage, b.uage);
  swap(a.__isset, b.__isset);
}

User::User(const User& other0) {
  uid = other0.uid;
  uname = other0.uname;
  usex = other0.usex;
  uage = other0.uage;
  __isset = other0.__isset;
}
User& User::operator=(const User& other1) {
  uid = other1.uid;
  uname = other1.uname;
  usex = other1.usex;
  uage = other1.uage;
  __isset = other1.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const User& obj) {
  using apache::thrift::to_string;
  out << "User(";
  out << "uid=" << to_string(obj.uid);
  out << ", " << "uname=" << to_string(obj.uname);
  out << ", " << "usex=" << to_string(obj.usex);
  out << ", " << "uage=" << to_string(obj.uage);
  out << ")";
  return out;
}


